version: '3.0'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
    - 3000:3000
    depends_on:
      - postgres
    command: npm run dev
    restart: always
  postgres:
    container_name: postgres
    image: postgres:14
    env_file:
    - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
    - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: